version: '3.8'

services:
  db:
    image: postgres:15-alpine # Using a specific, lightweight version
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=provisioning_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=your_strong_password_here
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://admin:your_strong_password_here@db/provisioning_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Standard port for Vite dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents local node_modules from overwriting container's
    stdin_open: true # Keeps the development server running interactively
    tty: true

volumes:
  postgres-data: