<script>
	import { onMount } from 'svelte';
	let accounts = [];
	let message = '';
	let isLoading = false;
	let showCommandModal = false;
	let commandToRun = '';

	// This is the command the application will show to the admin
	const powershellCommand = `Get-ADGroupMember -Identity "Your-Temp-Accounts-Group" | Select-Object displayName, userPrincipalName | Export-Csv -Path "C:\\temp\\temp_accounts.csv" -NoTypeInformation`;

	async function fetchAccounts() {
		const res = await fetch('/api/admin/temp-accounts');
		accounts = await res.json();
	}

	async function handleFileUpload(event) {
		const file = event.target.files[0];
		if (!file) return;

		isLoading = true;
		message = 'Uploading and processing...';

		const formData = new FormData();
		formData.append('file', file);

		try {
			const response = await fetch('/api/admin/upload-temp-accounts-csv', {
				method: 'POST',
				body: formData
			});
			const data = await response.json();
			if (!response.ok) throw new Error(data.detail || 'Failed to upload.');
			
			message = data.message;
			await fetchAccounts(); // Refresh the list
		} catch (error) {
			message = `Error: ${error.message}`;
		} finally {
			isLoading = false;
		}
	}

	async function toggleInUseStatus(account) {
		const newStatus = !account.is_in_use;
		try {
			const response = await fetch(`/api/admin/temp-accounts/${account.id}/status?is_in_use=${newStatus}`, {
				method: 'PUT'
			});
			const result = await response.json();
			if (!response.ok) throw new Error(result.detail);

			// Update the UI with the data from the backend response
			accounts = accounts.map(a => a.id === account.id ? result.updated_account : a);
			
			// Show the command in a modal
			commandToRun = result.powershell_command;
			showCommandModal = true;

		} catch (error) {
			alert(`Error: ${error.message}`);
		}
	}

	onMount(fetchAccounts);
</script>

<h2>Temporary Accounts Management</h2>

<div class="workflow-box">
	<h3>Step 1: Export from Active Directory</h3>
	<p>Copy the command below and run it in a PowerShell terminal that has the Active Directory module installed.</p>
	<textarea readonly>{powershellCommand}</textarea>
</div>

<div class="workflow-box">
	<h3>Step 2: Import the CSV File</h3>
	<p>Upload the `temp_accounts.csv` file generated by the command.</p>
	<input type="file" accept=".csv" on:change={handleFileUpload} disabled={isLoading} />
	{#if message}<p><i>{message}</i></p>{/if}
</div>

<h3>Cached TEMP Accounts</h3>
<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Display Name</th>
			<th>User Principal Name</th>
			<th>In Use?</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{#each accounts as acc (acc.id)}
			<tr>
				<td>{acc.id}</td>
				<td>{acc.display_name}</td>
				<td>{acc.user_principal_name}</td>
				<td>{acc.is_in_use ? 'Yes' : 'No'}</td>
				<td>
					<button on:click={() => toggleInUseStatus(acc)}>
						{acc.is_in_use ? 'Mark as Available' : 'Mark as In Use'}
					</button>
				</td>
			</tr>
		{/each}
	</tbody>
</table>

{#if showCommandModal}
<div class="modal-backdrop" on:click={() => showCommandModal = false}>
	<div class="modal" on:click|stopPropagation>
		<h4>PowerShell Command Generated</h4>
		<p>Run the following command in your PowerShell console to apply the change in Active Directory.</p>
		<textarea readonly>{commandToRun}</textarea>
		<button on:click={() => showCommandModal = false}>Close</button>
	</div>
</div>
{/if}

<style>
	.workflow-box {
		border: 1px solid #ccc;
		padding: 1rem;
		margin-bottom: 1rem;
		background-color: #f9f9f9;
	}
	textarea {
		width: 100%;
		font-family: monospace;
		padding: 0.5rem;
	}
	table {
		width: 100%;
		border-collapse: collapse;
		margin-top: 1rem;
	}
	th, td {
		border: 1px solid #ddd;
		padding: 0.5rem;
		text-align: left;
	}
	th {
		background-color: #f2f2f2;
	}
	button {
		background-color: #0066cc;
		color: white;
		border: none;
		padding: 0.5rem 1rem;
		cursor: pointer;
		border-radius: 3px;
	}
	button:hover {
		background-color: #0052a3;
	}
	.modal-backdrop {
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		background-color: rgba(0, 0, 0, 0.5);
		display: flex;
		justify-content: center;
		align-items: center;
		z-index: 1000;
	}
	.modal {
		background-color: white;
		padding: 2rem;
		border-radius: 5px;
		width: 80%;
		max-width: 600px;
		box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
	}
	.modal textarea {
		height: 100px;
		resize: vertical;
		margin: 1rem 0;
	}
	.modal button {
		margin-top: 1rem;
	}
</style>
