<script>
	import { onMount } from 'svelte';
	let accounts = [];
	let message = '';
	let isLoading = false;

	// This is the command the application will show to the admin
	const powershellCommand = `Get-ADGroupMember -Identity "Your-Temp-Accounts-Group" | Select-Object displayName, userPrincipalName | Export-Csv -Path "C:\\temp\\temp_accounts.csv" -NoTypeInformation`;

	async function fetchAccounts() {
		const res = await fetch('/api/admin/temp-accounts');
		accounts = await res.json();
	}

	async function handleFileUpload(event) {
		const file = event.target.files[0];
		if (!file) return;

		isLoading = true;
		message = 'Uploading and processing...';

		const formData = new FormData();
		formData.append('file', file);

		try {
			const response = await fetch('/api/admin/upload-temp-accounts-csv', {
				method: 'POST',
				body: formData
			});
			const data = await response.json();
			if (!response.ok) throw new Error(data.detail || 'Failed to upload.');
			
			message = data.message;
			await fetchAccounts(); // Refresh the list
		} catch (error) {
			message = `Error: ${error.message}`;
		} finally {
			isLoading = false;
		}
	}

	onMount(fetchAccounts);
</script>

<h2>Temporary Accounts Management</h2>

<div class="workflow-box">
	<h3>Step 1: Export from Active Directory</h3>
	<p>Copy the command below and run it in a PowerShell terminal that has the Active Directory module installed.</p>
	<textarea readonly>{powershellCommand}</textarea>
</div>

<div class="workflow-box">
	<h3>Step 2: Import the CSV File</h3>
	<p>Upload the `temp_accounts.csv` file generated by the command.</p>
	<input type="file" accept=".csv" on:change={handleFileUpload} disabled={isLoading} />
	{#if message}<p><i>{message}</i></p>{/if}
</div>

<h3>Cached TEMP Accounts</h3>
<table>
	<thead>
		<tr><th>ID</th><th>Display Name</th><th>User Principal Name</th><th>In Use?</th></tr>
	</thead>
	<tbody>
		{#each accounts as acc}
			<tr>
				<td>{acc.id}</td>
				<td>{acc.display_name}</td>
				<td>{acc.user_principal_name}</td>
				<td>{acc.is_in_use}</td>
			</tr>
		{/each}
	</tbody>
</table>

<style>
	.workflow-box {
		border: 1px solid #ccc;
		padding: 1rem;
		margin-bottom: 1rem;
		background-color: #f9f9f9;
	}
	textarea {
		width: 100%;
		font-family: monospace;
		padding: 0.5rem;
	}
	table {
		width: 100%;
		border-collapse: collapse;
		margin-top: 1rem;
	}
	th, td {
		border: 1px solid #ddd;
		padding: 0.5rem;
		text-align: left;
	}
	th {
		background-color: #f2f2f2;
	}
</style>
